<!-- SC_OFF --><div class="md"><p>Was able to launch it again, by following this <a href="https://www.reddit.com/r/archlinux/comments/vzc13m/psa_libnotify_update_breaks_gnometweaks/?utm_source=share&amp;utm_medium=web2x&amp;context=3">PSA</a> that was posted on the sub.</p> <p>Had to go to /usr/bin/gwe and change 0.7 to 0.8 on Line 47 to fix it.</p> <p>Last night (16-07-2022), iirc. gwe had an update and this morning (17-07-2022) gwe is not launching again.</p> <p>Had the same error:</p> <pre><code>Traceback (most recent call last): File &quot;/usr/bin/gwe&quot;, line 47, in &lt;module&gt; gi.require_version(&#39;Notify&#39;, &#39;0.8&#39;) File &quot;/usr/lib/python3.10/site-packages/gi/__init__.py&quot;, line 129, in require_version raise ValueError(&#39;Namespace %s not available for version %s&#39; % ValueError: Namespace Notify not available for version 0.8 </code></pre> <p>So, I tried to go back to /usr/bin/gwe and changed 0.8 back to 0.7 and it worked again.</p> <p>Idk. what to do with this information, so just wanted to share it here in case you guys are having the same problem.</p> </div><!-- SC_ON --> &#32; submitted by &#32; <a href="https://www.reddit.com/user/HeathenHacks"> /u/HeathenHacks </a> <br/> <span><a href="https://www.reddit.com/r/archlinux/comments/w0wud6/2_days_ago_i_cant_launch_gwe_greenwithenvy_after/">[link]</a></span> &#32; <span><a href="https://www.reddit.com/r/archlinux/comments/w0wud6/2_days_ago_i_cant_launch_gwe_greenwithenvy_after/">[comments]</a></span>